### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by rosscdh** [antonbabenko/terrapin#4]
Hi there,

I just started with terraform, was decidedly unimpressed with the pseudo templating features and considered starting a project just like this one. But then I discovered you had started work on it.

Might I ask the status of this project?

Thanks for your efforts on improving terraform!

**Comment by antonbabenko** [comment]
Hi Ross!

This project is not active.

I still believe that there is a need in such tool, but I have switched priorities from this project to [terraform-aws-modules](https://github.com/terraform-aws-modules) and [modules.tf](https://github.com/antonbabenko/modules.tf-lambda) some time ago.

Best regards,
Anton.

**Comment by rosscdh** [comment]
Pulumi ;) https://pulumi.io/quickstart/

**Comment by antonbabenko** [comment]
Nope :)

We know each other, but we are doing pretty different things.
